### ISSUE TITLE
Include Spotrac player IDs in roster.csv

### ISSUE THREAD

**Issue by nickwan** [nflverse/nflverse-rosters#29]
Hello, can yall please have Spotrac ID support available somewhere to join on? The spotrac ID looks unique to their site (i.e. Larry Fitzgerald's Spotrac ID is 966, while his NFL ID is 2506106, esb ID is FIT437493, gsis ID is 00-0022921, and college ID is 2927) 

Alternatively, if you ingest salary info into a roster file that would also be cool. bonus points for draft day info

**Comment by tanho63** [comment]
IDs shouldn’t be too tricky aside from the usual name join BS. Contract data definitely a bit more involved. 

Is OTC better than spotrac to store?

**Comment by mrcaseb** [comment]
I wrote a scraper that scrapes historical contract data from sites like this 
https://overthecap.com/contract-history/quarterback/
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/38586519/165120270-e5fcfebb-cb58-48ca-a0fe-6abaaf38ad76.png">

Data will look like this:
<img width="958" alt="image" src="https://user-images.githubusercontent.com/38586519/165120619-d00888b2-1faa-48da-a8e7-ffbf65e22b64.png">

I think the OTC IDs are not the same as spotrac IDs. Do you guys think this data is valuable in the nflverse @tanho63 and @nickwan? We could automate the scraper and add a function in nflreadr to load all historical contracts.

**Comment by tanho63** [comment]
100% useful!

**Comment by mrcaseb** [comment]
> I wrote a scraper that scrapes historical contract data from sites like this https://overthecap.com/contract-history/quarterback/ <img alt="image" width="1016" src="https://user-images.githubusercontent.com/38586519/165120270-e5fcfebb-cb58-48ca-a0fe-6abaaf38ad76.png">
> 
> Data will look like this: <img alt="image" width="958" src="https://user-images.githubusercontent.com/38586519/165120619-d00888b2-1faa-48da-a8e7-ffbf65e22b64.png">
> 
> I think the OTC IDs are not the same as spotrac IDs. Do you guys think this data is valuable in the nflverse @tanho63 and @nickwan? We could automate the scraper and add a function in nflreadr to load all historical contracts.

The current version of this data is now attached to this release https://github.com/nflverse/nflverse-data/releases/tag/otc_contract_data

**Comment by tanho63** [comment]
Update: after some discussion about naming it's now actually here lol https://github.com/nflverse/nflverse-data/releases/contracts 

Still TODO: gsis/nflverse id -> otc id

**Comment by mrcaseb** [comment]
otc data and IDs are done. I am not looking to support Spotrac because of the Spotrac <-> OTC issues and we get active support by OTC
