### ISSUE TITLE
PFR ID mismatch: Patrick Jones, Pacman Jones in `load_rosters` table

### ISSUE THREAD

**Issue by nickpietrantonio** [nflverse/nflverse-rosters#30]
The fast_scraper_roster table has two rows for each season of Patrick Jones, gsis_id 00-0037007. The only difference I am seeing in the rows is pfr_id, the correct rows have JonePa00 and the extra rows have JonePa20 which brings you to Adam "Pacman" Jones' page so I believe the JonePa20 row is an extra row that is unneeded. 

I noticed while checking; Adam Jones' actual rows, gsis_id 00-0023441, have no pfr_id listed.

**Comment by john-b-edwards** [comment]
Believe this issue has been resolved:

```r
nflreadr::load_rosters(2021:2023) |>
    dplyr::filter(gsis_id == '00-0037007') |>
    dplyr::select(season, full_name, gsis_id, pfr_id)
#> ── nflverse roster data ────────────────────────────────────────────────────────
#> ℹ Data updated: 2023-09-04 00:13:49 PDT
#> # A tibble: 3 × 4
#>   season full_name     gsis_id    pfr_id  
#>    <int> <chr>         <chr>      <chr>   
#> 1   2021 Patrick Jones 00-0037007 JonePa00
#> 2   2022 Patrick Jones 00-0037007 JonePa00
#> 3   2023 Patrick Jones 00-0037007 JonePa00
```
