### ISSUE TITLE
Incorrect draft_number and draft_club data

### ISSUE THREAD

**Issue by Adeiko** [nflverse/nflverse-rosters#55]
Used the latest update from dev 

> nflverse::nflverse_update(devel = TRUE)
✔ All nflverse packages are up-to-date!

The draft_club and draft_number info seems to be inconsistent in the db in most players. It shows different data for each year on the same player.  An example of Carson Palmer: 

```
nflreadr::load_rosters(2006:2021) %>% filter(full_name=="Carson Palmer")%>% select(season,draft_club,draft_number,entry_year)
   season draft_club draft_number entry_year
    <int> <chr>      <chr>        <chr>     
 1   2006 TEN        52           2003      
 2   2007 CIN        114          2003      
 3   2008 PHI        61           2003      
 4   2009 CIN        55           2003      
 5   2010 CIN        91           2003      
 6   2011 NE         6            2003      
 7   2011 NE         6            2003      
 8   2012 IND        93           2003      
 9   2013 DET        43           2003      
10   2015 OAK        69           2003      
11   2016 NA         NA           NA        
12   2017 NA         NA           NA 
```

I tried to to use the data from load_combine to merge it, this is an script that I used to get a couple of df with the inconsistent info. 

https://gist.github.com/Adeiko/018b8f5f7f242b8368a42009aabeff9a

**Comment by paulg66** [comment]
Are there any updates on getting a fix in for this?
