### ISSUE TITLE
Let's Brainstorm Player IDs

### ISSUE THREAD

**Issue by mrcaseb** [nflverse/nflverse-rosters#72]
I would like to collect IDs we should include in our player datasets. IDs have been a big problem in the last 1-2 years because mapping them to, e.g. gsis_ids, is sophisticated and buggy. We need automated processes that update esp. when Rookies enter the league. 

Here's what I think we should have at least:

- [x] gsis_id
- [x] pff_id
- [x] pfr_id
- [x] espn_id
- [x] otc_id

Fantasy people probably looking for stuff like

- [ ] sleeper
- [ ] mfl
- [ ]

**Comment by tanho63** [comment]
offhand I'm thinking of:

- sportradar_id (legacy, but still impt for fantasy fb)
- nextgen stats (i.e. gsis_it_id, I think?)
- college football reference id
- spotrac (if we ever actually scrape them)
- fleaflicker uses sportradar
- yahoo id 🤢 
- draftkings id
- fanduel id

I've also had request for [wikidata id](https://www.wikidata.org/wiki/Q7539)

**Comment by mrcaseb** [comment]
Many of the above is done in https://github.com/nflverse/nflverse-players

The remaining IDs will be maintained in ffverse.
