### ISSUE TITLE
Incorrect ESBID for Liam McCullough in roster_weekly_2023.csv file

### ISSUE THREAD

**Issue by DaSkunk** [nflverse/nflverse-rosters#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

I am not using an nflverse R package (nflreadr, nflfastR) to access this data.

### What version of the package do you have?

This relates to the roster_weekly_2023.csv file

### Describe the bug

Tan
 — 
Today at 7:27 PM
Can you open an issue in nflverse/nflverse-rosters? unsure when we might get to it but it’s good to centralize all issues together

I'm not absolutely certain but there may be a mistake in the roster_weekly_2023.csv in nflverse/nflverse-data under players release. If I am correct I just wanted to bring it to your attention. I think the ESBID for Liam McCullough may be incorrect. Here's a snipit of his entries in the roster_weekly csv.

```
2023,ATL,LS,LS,49,ACT,Liam McCullough,Liam,McCullough,1997-06-05,74,237,Ohio State,00-0036082,,,,,,,,,3,"[https://static.www.nfl.com/image/private/f_auto,q_auto/league/fdwbtbdsntzlgld87c5w",,14,REG,A01,Liam,MCC769873,52986,3200474f-5204-5716-a75e-4ec8e313a651,2020,2020](https://static.www.nfl.com/image/private/f_auto,q_auto/league/fdwbtbdsntzlgld87c5w%22,,14,REG,A01,Liam,MCC769873,52986,3200474f-5204-5716-a75e-4ec8e313a651,2020,2020),,
2023,ATL,LS,LS,49,ACT,Liam McCullough,Liam,McCullough,1997-06-05,74,237,Ohio State,00-0036082,,,,,,,,,3,"[https://static.www.nfl.com/image/private/f_auto,q_auto/league/fdwbtbdsntzlgld87c5w",,13,REG,A01,Liam,MCC769873,52986,3200474f-5204-5716-a75e-4ec8e313a651,2020,2020](https://static.www.nfl.com/image/private/f_auto,q_auto/league/fdwbtbdsntzlgld87c5w%22,,13,REG,A01,Liam,MCC769873,52986,3200474f-5204-5716-a75e-4ec8e313a651,2020,2020),,
```

Based on the info in Sunday's game json, coupled with info I have from week 5 pbp_patch_ids_2023.csv, I believe the correct ESBID is
32004d43-4376-9873-8228-cd33f90cba27

Thank you

### Reprex

```r
I am not running any code just reading the information from the roster_weekly_2023.csv file
```

### Expected Behavior

NA

### nflverse_sitrep

```r
NA
```

### Screenshots

```markdown
NA
```

**Comment by mrcaseb** [comment]
You are absolutely right. 

The PBP ID `3200474f-5204-5716-a75e-4ec8e313a651` hashes Anthony Gordnon's ESB ID `GOR045716`. 
The correct PBP ID is `32004d43-4376-9873-8228-cd33f90cba27` which hashes `MCC769873`, the ESB ID of Liam McCullough

**Comment by john-b-edwards** [comment]
Checking the csv now, I see only the correct ESB ID for McCullough:

```r
nflreadr:::csv_from_url('https://github.com/nflverse/nflverse-data/releases/download/weekly_rosters/roster_weekly_2023.csv') |>
    dplyr::filter(gsis_id == "00-0036082") |>
    dplyr::count(esb_id)
#>       esb_id  n
#> 1: MCC769873 17
```

Furthermore, I see that it's correct across all of our roster files:

```r
nflreadr::load_rosters(T) |>
    dplyr::filter(gsis_id == "00-0036082") |>
    dplyr::count(esb_id)
#> ── nflverse roster data ────────────────────────────────────────────────────────
#> ℹ Data updated: 2024-08-04 00:11:42 PDT
#> # A tibble: 1 × 2
#>   esb_id        n
#>   <chr>     <int>
#> 1 MCC769873     4

nflreadr::load_rosters_weekly(T) |>
    dplyr::filter(gsis_id == "00-0036082") |>
    dplyr::count(esb_id)
#> ── nflverse weekly roster data ─────────────────────────────────────────────────
#> ℹ Data updated: 2024-08-04 00:11:22 PDT
#> # A tibble: 1 × 2
#>   esb_id        n
#>   <chr>     <int>
#> 1 MCC769873    36

nflreadr::load_players() |>
    dplyr::filter(gsis_id == "00-0036082") |>
    dplyr::count(esb_id)
#> ── nflverse players ────────────────────────────────────────────────────────────
#> ℹ Data updated: 2024-07-31 18:29:00 PDT
#> # A tibble: 1 × 2
#>   esb_id        n
#>   <chr>     <int>
#> 1 MCC769873     1
```

I'm assuming NFL fixed this on their end, and then our automatic processes picked up the fix. Regardless, going to mark this as closed unless we can find a messed up `esb_id` elsewhere.

**Comment by DaSkunk** [comment]
Thank you for looking into this.  My apologies ... I may have cited the wrong field in the original post. I just looked at the latest roster_weekly_2024.csv posted 6 hours ago and the problem still appears to be there.  I was referring to the 3200474f-5204-5716-a75e-4ec8e313a651 value in what looks like the "smart_id" field (column AF in spreadsheet form).  I apologize if I said esb_id and sent you down the wrong path. Could you please check again because I have game json and a prior weekly_roster_file from 2023 which indicated the smart_id should be 32004d43-4376-9873-8228-cd33f90cba27.  Thank you again.
