### ISSUE TITLE
[BUG] <title>Inadvertent LF-CR combination in game json ... maybe?

### ISSUE THREAD

**Issue by DaSkunk** [nflverse/nflverse-rosters#83]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

I am not using an nflverse R package (nflreadr, nflfastR) to access this data.

### What version of the package do you have?

This relates to the json.gz game json files in https://github.com/nflverse/nflfastR-raw/tree/master/raw/2023

### Describe the bug

This may or may not be a problem, and if it is not then my apologies and feel free to close the issue. I've never seen this prior to the 2023 season game json which is why I'm questioning it.  In many of the 2023 game json files there are CR-LF (\r\n) combinations inserted in the play description. Strangely enough they only seem to appear in front of the word PENALTY. Here is a sample from the opening day (Sept 7, 2023) Chiefs vs Lions game.

 "playDescription": "(1:13) (Shotgun) P.Mahomes pass short middle to N.Gray to DET 48 for 6 yards (K.Joseph).\r\nPENALTY on KC-T.Smith, Offensive Holding, 10 yards, enforced at KC 46 - No Play.", 
 
 Again if this is technically not a problem and is intended, then please close the issue and my apologies for bothering you. Thank you.
                        "p

### Reprex

```r
Please just look inside the 2023_01_DET_KC.json.gz file in https://github.com/nflverse/nflfastR-raw/tree/master/raw/2023
```

### Expected Behavior

I wasn't expecting the \r\n characters to appear in the play description field

### nflverse_sitrep

```r
NA
```

### Screenshots

```markdown
NA
```

### Additional context

NA

**Comment by JimHewitt** [comment]
I also use the raw data from https://github.com/nflverse/nflverse-pbp/releases and I don't have those characters in the description for that play.

**Comment by tanho63** [comment]
We do not recommend folks use the json.gz and we aim to keep that as close to the original raw file as possible - the parsed files are what we consider cleaned and maintained products. 

Closing as not planned

**Comment by JimHewitt** [comment]
Does this mean you will not be populating https://github.com/nflverse/nflverse-pbp/releases with the raw data?

**Comment by tanho63** [comment]
Yes, we will still be populating it, but we don’t bugfix or maintain the files themselves since they’re raw data storage

**Comment by DaSkunk** [comment]
Thank you very much for looking into it and I completely understand the decision. Appreciate your time on this and I'm fine with closing it.
