### ISSUE TITLE
[BUG] 2024 Week 4 injuries are missing

### ISSUE THREAD

**Issue by nateb7722** [nflverse/nflverse-rosters#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

I am not using an nflverse R package (nflreadr, nflfastR) to access this data.

### What version of the package do you have?

0.3.1

### Describe the bug

import_injuries function does not return data for week 4, all other weeks have injury reports

### Reprex

```r
import nfl_data_py as nfl
inj = nfl.import_injuries([2024])
inj['week'].unique()
```

### Expected Behavior

as of this moment weeks 1-5 should all have data

### nflverse_sitrep

```r
NA
```

**Comment by john-b-edwards** [comment]
Unfortunately, 2024 injury data was not uploaded to the NFL data exchange, so we can't pull this data down at this time:

```r
> scrape_ir(2024, 4, "REG")
data frame with 0 columns and 0 rows
```

As it's an issue with missing data, there's not much we can do here. If the NFL does re-upload this missing data, our automated process should pick it up when it becomes available.

I'm going to leave this issue open and tag it as WONTFIX to ensure that if anyone else notices that it's missing, they'll know we're aware.
